//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFHexagonalDDD.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENTALS
    {
        public string ID { get; set; }
        public string VEHICLE_ID { get; set; }
        public string CUSTOMER_ID { get; set; }
        public System.DateTime RENTAL_DATE { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        public virtual VEHICLES VEHICLES { get; set; }
    }
}
