//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFHexagonalDDD.Infraestructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICLES()
        {
            this.RENTALS = new HashSet<RENTALS>();
        }
    
        public string ID { get; set; }
        public string REGISTRATION_NUMBER { get; set; }
        public string BRAND { get; set; }
        public string MODEL { get; set; }
        public System.DateTime MANUFACTURE_DATE { get; set; }
        public string STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTALS> RENTALS { get; set; }
    }
}
