ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER RENTING
IDENTIFIED BY Renting123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO RENTING;
GRANT CREATE TABLE TO RENTING;
GRANT CREATE SEQUENCE TO RENTING;
GRANT CREATE VIEW TO RENTING;
GRANT UNLIMITED TABLESPACE TO RENTING;