SET SQLBLANKLINES ON
ALTER SESSION SET CONTAINER = FREEPDB1;

ALTER SESSION SET CURRENT_SCHEMA = RENTING;

CREATE TABLE CUSTOMERS
(
    ID   VARCHAR2(36)  NOT NULL,
    NAME VARCHAR2(150) NOT NULL,

    CONSTRAINT PK_CUSTOMERS
        PRIMARY KEY (ID)
);

CREATE TABLE VEHICLES
(
    ID                  VARCHAR2(36)  NOT NULL,
    REGISTRATION_NUMBER VARCHAR2(20)  NOT NULL,
    BRAND               VARCHAR2(100) NOT NULL,
    MODEL               VARCHAR2(100) NOT NULL,
    MANUFACTURE_DATE    DATE          NOT NULL,
    STATUS              VARCHAR2(20)  NOT NULL,

    CONSTRAINT PK_VEHICLES
        PRIMARY KEY (ID),

    CONSTRAINT UQ_VEHICLES_REGISTRATION
        UNIQUE (REGISTRATION_NUMBER),

    CONSTRAINT CK_VEHICLES_STATUS
        CHECK (STATUS IN ('Available', 'Rented'))
);

CREATE TABLE RENTALS
(
    ID          VARCHAR2(36) NOT NULL,
    VEHICLE_ID  VARCHAR2(36) NOT NULL,
    CUSTOMER_ID VARCHAR2(36) NOT NULL,
    RENTAL_DATE DATE         NOT NULL,
    RETURN_DATE DATE,

    CONSTRAINT PK_RENTALS
        PRIMARY KEY (ID),

    CONSTRAINT FK_RENTALS_VEHICLES
        FOREIGN KEY (VEHICLE_ID)
        REFERENCES VEHICLES (ID),

    CONSTRAINT FK_RENTALS_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS (ID)
);